version: '3'
services:
  predictor:
    ports:
    - "4000:4000"
    extra_hosts:
      - "localhost:$DOCKERHOST"
    build:
      context: .
    command: python predictor_server.py
    image: mgamga/color-summarizer
  colors:
    build:
      context: .
      dockerfile: Dockerfile-ruby
    command: bundle exec ruby app.rb
    ports:
    - "4567:4567"
    extra_hosts:
      - "localhost:$DOCKERHOST"
    environment:
      - RAILS_ENV=production
      - RACK_ENV=production
    image: mgamga/color-summarizer