version: '3'
services:
  predictor:
    ports:
    - "4000:4000"
    extra_hosts:
      - "localhost:$DOCKERHOST"
    build:
      context: .
    command: python predictor_server.py
    image: mgamga/color-summarizer
  colors:
    build:
      context: .
    command: python app.py
    ports:
    - "5000:5000"
    extra_hosts:
      - "localhost:$DOCKERHOST"
    image: mgamga/color-summarizer